name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  # ~~~~~~~~~~~~~~~~~~ Cypress v9 and below (using Legacy configuration) ~~~~~~~~~~~~~~~~~~~ #

  basic-ubuntu-20-v9:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy to AWS CloudFormation
        # normally you would write
        # uses: cypress-io/github-action@v5
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          name: MyStack
          template: ec2-instance.yaml
          parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
